In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

In [4]:
diabetes = load_diabetes()

X = pd.DataFrame(
    diabetes.data,
    columns = diabetes.feature_names
)

y = diabetes.target

In [5]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [6]:
X.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [8]:
X.shape

(442, 10)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
linear = LinearRegression()

In [11]:
linear.fit(X_train, y_train)

LinearRegression()

In [12]:
linear_prediction = linear.predict(X_test)

In [13]:
mse = mean_squared_error(y_test, linear_prediction)

rmse = root_mean_squared_error(y_test, linear_prediction)

r2 = r2_score(y_test, linear_prediction)

In [14]:
print(f'MSE: {mse:.2f}')
print(f'RMSE: {rmse:.2f}')
print(f'R2: {r2:.2f}')

MSE: 2900.19
RMSE: 53.85
R2: 0.45

In [15]:
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": linear.coef_
})

coef_df = coef_df.sort_values(
    by = "Coefficient",
    key = abs,
    ascending = False
)

coef_df

  Feature  Coefficient
4      s1  -931.488846
8      s5   736.198859
2     bmi   542.428759
5      s2   518.062277
3      bp   347.703844
7      s4   275.317902
1     sex  -241.964362
6      s3   163.419983
9      s6    48.670657
0     age    37.904021

In [16]:
train_prediction = linear.predict(X_train)

In [17]:
print(
    "Train: R2: ",
    r2_score(y_train, train_prediction)
)
print(
    "Test: R2: ",
    r2_score(y_test, linear_prediction)
)

Train: R2:  0.5279193863361498
Test: R2:  0.4526027629719195

In [18]:
ridge = Ridge(alpha=1.0)

ridge.fit(X_train, y_train)

Ridge()

In [19]:
ridge_prediction = ridge.predict(X_test)

In [20]:
ridge_mse = mean_squared_error(y_test, ridge_prediction)

ridge_rmse = root_mean_squared_error(y_test, ridge_prediction)

ridge_r2 = r2_score(y_test, ridge_prediction)

print(f'MSE: {ridge_mse:.2f}')
print(f'RMSE: {ridge_rmse:.2f}')
print(f'R2: {ridge_r2:.2f}')

MSE: 3077.42
RMSE: 55.47
R2: 0.42

In [21]:
ridge_train_prediction = ridge.predict(X_train)

print(
    "Train: R2: ",
    r2_score(y_train, ridge_train_prediction)
)
print(
    "Test: R2: ",
    r2_score(y_test, ridge_prediction)
)

Train: R2:  0.4424027835503952
Test: R2:  0.41915292635986545

In [22]:
ridge_coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": ridge.coef_
})

In [23]:
comparison = coef_df.merge(
    ridge_coef,
    on="Feature"
)
comparison

  Feature  Coefficient_x  Coefficient_y
0      s1    -931.488846      -0.530310
1      s5     736.198859     230.221608
2     bmi     542.428759     291.338832
3      s2     518.062277     -28.577050
4      bp     347.703844     198.995817
5      s4     275.317902     119.260066
6     sex    -241.964362     -76.666086
7      s3     163.419983    -144.511905
8      s6      48.670657     112.149830
9     age      37.904021      45.367377

In [24]:
comparison = comparison.rename(columns={
    "Coefficient_x": "Linear",
    "Coefficient_y": "Ridge"
})
comparison['Linear Abs'] = comparison['Linear'].abs()
comparison['Ridge Abs'] = comparison['Ridge'].abs()

comparison = comparison.sort_values(
    by="Linear Abs",
    ascending=False
)

comparison

  Feature      Linear       Ridge  Linear Abs   Ridge Abs
0      s1 -931.488846   -0.530310  931.488846    0.530310
1      s5  736.198859  230.221608  736.198859  230.221608
2     bmi  542.428759  291.338832  542.428759  291.338832
3      s2  518.062277  -28.577050  518.062277   28.577050
4      bp  347.703844  198.995817  347.703844  198.995817
5      s4  275.317902  119.260066  275.317902  119.260066
6     sex -241.964362  -76.666086  241.964362   76.666086
7      s3  163.419983 -144.511905  163.419983  144.511905
8      s6   48.670657  112.149830   48.670657  112.149830
9     age   37.904021   45.367377   37.904021   45.367377

In [25]:
lasso = Lasso(alpha=1.0)

lasso.fit(X_train, y_train)

Lasso()

In [26]:
lasso_predictions = lasso.predict(X_test)

In [27]:
lasso_mse = mean_squared_error(y_test, lasso_predictions)

lasso_rmse = root_mean_squared_error(y_test, lasso_predictions)

lasso_r2 = r2_score(y_test, lasso_predictions)

print(f'MSE: {lasso_mse:.2f}')
print(f'RMSE: {lasso_rmse:.2f}')
print(f'R2: {lasso_r2:.2f}')

MSE: 3403.58
RMSE: 58.34
R2: 0.36

In [29]:
lasso_coef = pd.DataFrame({
    "Feature":X.columns,
    "Lasso":lasso.coef_
})
lasso_coef

  Feature       Lasso
0     age    0.000000
1     sex   -0.000000
2     bmi  413.431848
3      bp   34.830515
4      s1    0.000000
5      s2    0.000000
6      s3   -0.000000
7      s4    0.000000
8      s5  258.152894
9      s6    0.000000

In [30]:
comparison = pd.DataFrame({
    "Feature":X.columns,
    "Linear":linear.coef_,
    "Ridge":ridge.coef_,
    "Lasso":lasso.coef_
})

comparison

  Feature      Linear       Ridge       Lasso
0     age   37.904021   45.367377    0.000000
1     sex -241.964362  -76.666086   -0.000000
2     bmi  542.428759  291.338832  413.431848
3      bp  347.703844  198.995817   34.830515
4      s1 -931.488846   -0.530310    0.000000
5      s2  518.062277  -28.577050    0.000000
6      s3  163.419983 -144.511905   -0.000000
7      s4  275.317902  119.260066    0.000000
8      s5  736.198859  230.221608  258.152894
9      s6   48.670657  112.149830    0.000000

In [31]:
print(
    "Number of selected features:",
    np.sum(lasso.coef_ != 0)
)

Number of selected features: 3